language: python
python:
  - "3.6"

sudo: false

stages:
  - test
  - bundle
  - name: deploy
    if: tag =~ /^v\d+\.\d+\.\d+$/ AND repo = HaaLeo/ant-colony-optimization

install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: test
      script:
        - python -m pylint ./*/*.py
    - stage: bundle
      script:
        - python setup.py sdist bdist_wheel
    - stage: deploy
      before_deploy:
        - python setup.py sdist bdist_wheel
        - twine upload dist/* -u HaaLeo -p ${PYPI_PASSWORD}
      script: skip
      deploy:
        provider: releases
        file_glob: true
        file: "dist/*"
        api_key: ${TRAVIS_CD}
        skip_cleanup: true
        on:
          tags: true
